# fly.toml app configuration file generated for domodel-chat-server on 2023-08-14T14:14:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "domodel-chat-server"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  processes = ["app"]
